(cl:in-package tb3_distributed_control-msg)
(cl:export '(ROBOT_ID-VAL
          ROBOT_ID
          TRAJECTORY_TIME-VAL
          TRAJECTORY_TIME
          ROS_TIMESTAMP-VAL
          ROS_TIMESTAMP
          XC-VAL
          XC
          YC-VAL
          YC
          THETAC-VAL
          THETAC
          VC-VAL
          VC
          WC-VAL
          WC
          XE-VAL
          XE
          YE-VAL
          YE
          THETAE-VAL
          THETAE
          XR-VAL
          XR
          YR-VAL
          YR
          ZXEO_X-VAL
          ZXEO_X
          ZXEO_Y-VAL
          ZXEO_Y
          RAW_MIN_OBSTACLE_DISTANCE-VAL
          RAW_MIN_OBSTACLE_DISTANCE
          CLOSEST_OBSTACLE_DISTANCE-VAL
          CLOSEST_OBSTACLE_DISTANCE
          TOTAL_CLUSTERS_COUNT-VAL
          TOTAL_CLUSTERS_COUNT
          AVOIDANCE_FORCE_MAGNITUDE-VAL
          AVOIDANCE_FORCE_MAGNITUDE
          COMPUTATION_TIME-VAL
          COMPUTATION_TIME
          FULL_CYCLE_TIME-VAL
          FULL_CYCLE_TIME
))