// Generated by gencpp from file tb3_distributed_control/LeaderHistoryData.msg
// DO NOT EDIT!


#ifndef TB3_DISTRIBUTED_CONTROL_MESSAGE_LEADERHISTORYDATA_H
#define TB3_DISTRIBUTED_CONTROL_MESSAGE_LEADERHISTORYDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb3_distributed_control
{
template <class ContainerAllocator>
struct LeaderHistoryData_
{
  typedef LeaderHistoryData_<ContainerAllocator> Type;

  LeaderHistoryData_()
    : trajectory_time(0.0)
    , ros_timestamp(0.0)
    , x0(0.0)
    , y0(0.0)
    , theta0(0.0)
    , v0(0.0)
    , w0(0.0)
    , u0x(0.0)
    , u0y(0.0)  {
    }
  LeaderHistoryData_(const ContainerAllocator& _alloc)
    : trajectory_time(0.0)
    , ros_timestamp(0.0)
    , x0(0.0)
    , y0(0.0)
    , theta0(0.0)
    , v0(0.0)
    , w0(0.0)
    , u0x(0.0)
    , u0y(0.0)  {
  (void)_alloc;
    }



   typedef double _trajectory_time_type;
  _trajectory_time_type trajectory_time;

   typedef double _ros_timestamp_type;
  _ros_timestamp_type ros_timestamp;

   typedef double _x0_type;
  _x0_type x0;

   typedef double _y0_type;
  _y0_type y0;

   typedef double _theta0_type;
  _theta0_type theta0;

   typedef double _v0_type;
  _v0_type v0;

   typedef double _w0_type;
  _w0_type w0;

   typedef double _u0x_type;
  _u0x_type u0x;

   typedef double _u0y_type;
  _u0y_type u0y;





  typedef boost::shared_ptr< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> const> ConstPtr;

}; // struct LeaderHistoryData_

typedef ::tb3_distributed_control::LeaderHistoryData_<std::allocator<void> > LeaderHistoryData;

typedef boost::shared_ptr< ::tb3_distributed_control::LeaderHistoryData > LeaderHistoryDataPtr;
typedef boost::shared_ptr< ::tb3_distributed_control::LeaderHistoryData const> LeaderHistoryDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator1> & lhs, const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator2> & rhs)
{
  return lhs.trajectory_time == rhs.trajectory_time &&
    lhs.ros_timestamp == rhs.ros_timestamp &&
    lhs.x0 == rhs.x0 &&
    lhs.y0 == rhs.y0 &&
    lhs.theta0 == rhs.theta0 &&
    lhs.v0 == rhs.v0 &&
    lhs.w0 == rhs.w0 &&
    lhs.u0x == rhs.u0x &&
    lhs.u0y == rhs.u0y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator1> & lhs, const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tb3_distributed_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e13ef0559dc1ccb0a5a11bd1a53b8ab3";
  }

  static const char* value(const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe13ef0559dc1ccb0ULL;
  static const uint64_t static_value2 = 0xa5a11bd1a53b8ab3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb3_distributed_control/LeaderHistoryData";
  }

  static const char* value(const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ROS话题优化版本：领导者历史数据消息类型\n"
"\n"
"# 时间戳信息\n"
"float64 trajectory_time    # 轨迹相对时间（从0开始）\n"
"float64 ros_timestamp     # ROS时间戳\n"
"\n"
"# 位置和姿态数据  \n"
"float64 x0               # 领导者x坐标\n"
"float64 y0               # 领导者y坐标\n"
"float64 theta0           # 领导者航向角\n"
"\n"
"# 速度数据\n"
"float64 v0               # 线速度\n"
"float64 w0               # 角速度\n"
"float64 u0x              # x方向速度分量\n"
"float64 u0y              # y方向速度分量\n"
;
  }

  static const char* value(const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory_time);
      stream.next(m.ros_timestamp);
      stream.next(m.x0);
      stream.next(m.y0);
      stream.next(m.theta0);
      stream.next(m.v0);
      stream.next(m.w0);
      stream.next(m.u0x);
      stream.next(m.u0y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeaderHistoryData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb3_distributed_control::LeaderHistoryData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_time: ";
    Printer<double>::stream(s, indent + "  ", v.trajectory_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ros_timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.ros_timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x0: ";
    Printer<double>::stream(s, indent + "  ", v.x0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y0: ";
    Printer<double>::stream(s, indent + "  ", v.y0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "theta0: ";
    Printer<double>::stream(s, indent + "  ", v.theta0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v0: ";
    Printer<double>::stream(s, indent + "  ", v.v0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "w0: ";
    Printer<double>::stream(s, indent + "  ", v.w0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "u0x: ";
    Printer<double>::stream(s, indent + "  ", v.u0x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "u0y: ";
    Printer<double>::stream(s, indent + "  ", v.u0y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB3_DISTRIBUTED_CONTROL_MESSAGE_LEADERHISTORYDATA_H
