// Generated by gencpp from file tb3_distributed_control/RobotHistoryData.msg
// DO NOT EDIT!


#ifndef TB3_DISTRIBUTED_CONTROL_MESSAGE_ROBOTHISTORYDATA_H
#define TB3_DISTRIBUTED_CONTROL_MESSAGE_ROBOTHISTORYDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tb3_distributed_control
{
template <class ContainerAllocator>
struct RobotHistoryData_
{
  typedef RobotHistoryData_<ContainerAllocator> Type;

  RobotHistoryData_()
    : robot_id(0)
    , trajectory_time(0.0)
    , ros_timestamp(0.0)
    , xc(0.0)
    , yc(0.0)
    , thetac(0.0)
    , vc(0.0)
    , wc(0.0)
    , xe(0.0)
    , ye(0.0)
    , thetae(0.0)
    , xr(0.0)
    , yr(0.0)
    , zxeo_x(0.0)
    , zxeo_y(0.0)
    , raw_min_obstacle_distance(0.0)
    , closest_obstacle_distance(0.0)
    , total_clusters_count(0)
    , avoidance_force_magnitude(0.0)
    , computation_time(0.0)
    , full_cycle_time(0.0)  {
    }
  RobotHistoryData_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , trajectory_time(0.0)
    , ros_timestamp(0.0)
    , xc(0.0)
    , yc(0.0)
    , thetac(0.0)
    , vc(0.0)
    , wc(0.0)
    , xe(0.0)
    , ye(0.0)
    , thetae(0.0)
    , xr(0.0)
    , yr(0.0)
    , zxeo_x(0.0)
    , zxeo_y(0.0)
    , raw_min_obstacle_distance(0.0)
    , closest_obstacle_distance(0.0)
    , total_clusters_count(0)
    , avoidance_force_magnitude(0.0)
    , computation_time(0.0)
    , full_cycle_time(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef double _trajectory_time_type;
  _trajectory_time_type trajectory_time;

   typedef double _ros_timestamp_type;
  _ros_timestamp_type ros_timestamp;

   typedef double _xc_type;
  _xc_type xc;

   typedef double _yc_type;
  _yc_type yc;

   typedef double _thetac_type;
  _thetac_type thetac;

   typedef double _vc_type;
  _vc_type vc;

   typedef double _wc_type;
  _wc_type wc;

   typedef double _xe_type;
  _xe_type xe;

   typedef double _ye_type;
  _ye_type ye;

   typedef double _thetae_type;
  _thetae_type thetae;

   typedef double _xr_type;
  _xr_type xr;

   typedef double _yr_type;
  _yr_type yr;

   typedef double _zxeo_x_type;
  _zxeo_x_type zxeo_x;

   typedef double _zxeo_y_type;
  _zxeo_y_type zxeo_y;

   typedef double _raw_min_obstacle_distance_type;
  _raw_min_obstacle_distance_type raw_min_obstacle_distance;

   typedef double _closest_obstacle_distance_type;
  _closest_obstacle_distance_type closest_obstacle_distance;

   typedef int32_t _total_clusters_count_type;
  _total_clusters_count_type total_clusters_count;

   typedef double _avoidance_force_magnitude_type;
  _avoidance_force_magnitude_type avoidance_force_magnitude;

   typedef double _computation_time_type;
  _computation_time_type computation_time;

   typedef double _full_cycle_time_type;
  _full_cycle_time_type full_cycle_time;





  typedef boost::shared_ptr< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> const> ConstPtr;

}; // struct RobotHistoryData_

typedef ::tb3_distributed_control::RobotHistoryData_<std::allocator<void> > RobotHistoryData;

typedef boost::shared_ptr< ::tb3_distributed_control::RobotHistoryData > RobotHistoryDataPtr;
typedef boost::shared_ptr< ::tb3_distributed_control::RobotHistoryData const> RobotHistoryDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator1> & lhs, const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator2> & rhs)
{
  return lhs.robot_id == rhs.robot_id &&
    lhs.trajectory_time == rhs.trajectory_time &&
    lhs.ros_timestamp == rhs.ros_timestamp &&
    lhs.xc == rhs.xc &&
    lhs.yc == rhs.yc &&
    lhs.thetac == rhs.thetac &&
    lhs.vc == rhs.vc &&
    lhs.wc == rhs.wc &&
    lhs.xe == rhs.xe &&
    lhs.ye == rhs.ye &&
    lhs.thetae == rhs.thetae &&
    lhs.xr == rhs.xr &&
    lhs.yr == rhs.yr &&
    lhs.zxeo_x == rhs.zxeo_x &&
    lhs.zxeo_y == rhs.zxeo_y &&
    lhs.raw_min_obstacle_distance == rhs.raw_min_obstacle_distance &&
    lhs.closest_obstacle_distance == rhs.closest_obstacle_distance &&
    lhs.total_clusters_count == rhs.total_clusters_count &&
    lhs.avoidance_force_magnitude == rhs.avoidance_force_magnitude &&
    lhs.computation_time == rhs.computation_time &&
    lhs.full_cycle_time == rhs.full_cycle_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator1> & lhs, const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tb3_distributed_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23ba331a962f095047cf39372dc8fff3";
  }

  static const char* value(const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23ba331a962f0950ULL;
  static const uint64_t static_value2 = 0x47cf39372dc8fff3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tb3_distributed_control/RobotHistoryData";
  }

  static const char* value(const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ROS话题优化版本：机器人历史数据消息类型\n"
"# 设计目标：减少网络传输，提高实时性，降低roscore负载\n"
"\n"
"# 机器人标识\n"
"int32 robot_id\n"
"\n"
"# 时间戳信息\n"
"float64 trajectory_time    # 轨迹相对时间（从0开始）\n"
"float64 ros_timestamp     # ROS时间戳（用于数据时效性检查）\n"
"\n"
"# 位置和姿态数据\n"
"float64 xc               # 当前x坐标\n"
"float64 yc               # 当前y坐标  \n"
"float64 thetac           # 当前航向角\n"
"\n"
"# 控制输入数据\n"
"float64 vc               # 线速度\n"
"float64 wc               # 角速度\n"
"\n"
"# 跟踪误差数据\n"
"float64 xe               # x方向误差\n"
"float64 ye               # y方向误差\n"
"float64 thetae           # 航向角误差\n"
"\n"
"# 参考轨迹数据\n"
"float64 xr               # 参考x坐标\n"
"float64 yr               # 参考y坐标\n"
"\n"
"# 观测器估计数据（对领导者位置的估计）\n"
"float64 zxeo_x           # 观测器估计的领导者X坐标\n"
"float64 zxeo_y           # 观测器估计的领导者Y坐标\n"
"\n"
"# 避障相关数据（统一处理所有障碍物）\n"
"float64 raw_min_obstacle_distance   # 雷达原始数据的最小距离（直接从range获取）\n"
"float64 closest_obstacle_distance   # 最近障碍物点到参考点的距离（基于聚类分析）\n"
"int32 total_clusters_count          # 检测到的障碍物聚类总数\n"
"float64 avoidance_force_magnitude   # 避障力大小\n"
"\n"
"# 性能分析数据\n"
"float64 computation_time  # 算法计算时间（秒）\n"
"float64 full_cycle_time  # 完整周期时间（秒）\n"
;
  }

  static const char* value(const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.trajectory_time);
      stream.next(m.ros_timestamp);
      stream.next(m.xc);
      stream.next(m.yc);
      stream.next(m.thetac);
      stream.next(m.vc);
      stream.next(m.wc);
      stream.next(m.xe);
      stream.next(m.ye);
      stream.next(m.thetae);
      stream.next(m.xr);
      stream.next(m.yr);
      stream.next(m.zxeo_x);
      stream.next(m.zxeo_y);
      stream.next(m.raw_min_obstacle_distance);
      stream.next(m.closest_obstacle_distance);
      stream.next(m.total_clusters_count);
      stream.next(m.avoidance_force_magnitude);
      stream.next(m.computation_time);
      stream.next(m.full_cycle_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotHistoryData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tb3_distributed_control::RobotHistoryData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory_time: ";
    Printer<double>::stream(s, indent + "  ", v.trajectory_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ros_timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.ros_timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xc: ";
    Printer<double>::stream(s, indent + "  ", v.xc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yc: ";
    Printer<double>::stream(s, indent + "  ", v.yc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thetac: ";
    Printer<double>::stream(s, indent + "  ", v.thetac);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vc: ";
    Printer<double>::stream(s, indent + "  ", v.vc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "wc: ";
    Printer<double>::stream(s, indent + "  ", v.wc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xe: ";
    Printer<double>::stream(s, indent + "  ", v.xe);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ye: ";
    Printer<double>::stream(s, indent + "  ", v.ye);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thetae: ";
    Printer<double>::stream(s, indent + "  ", v.thetae);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xr: ";
    Printer<double>::stream(s, indent + "  ", v.xr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yr: ";
    Printer<double>::stream(s, indent + "  ", v.yr);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "zxeo_x: ";
    Printer<double>::stream(s, indent + "  ", v.zxeo_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "zxeo_y: ";
    Printer<double>::stream(s, indent + "  ", v.zxeo_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "raw_min_obstacle_distance: ";
    Printer<double>::stream(s, indent + "  ", v.raw_min_obstacle_distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "closest_obstacle_distance: ";
    Printer<double>::stream(s, indent + "  ", v.closest_obstacle_distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_clusters_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.total_clusters_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "avoidance_force_magnitude: ";
    Printer<double>::stream(s, indent + "  ", v.avoidance_force_magnitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "computation_time: ";
    Printer<double>::stream(s, indent + "  ", v.computation_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "full_cycle_time: ";
    Printer<double>::stream(s, indent + "  ", v.full_cycle_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TB3_DISTRIBUTED_CONTROL_MESSAGE_ROBOTHISTORYDATA_H
