# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tb3_distributed_control/LeaderHistoryData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LeaderHistoryData(genpy.Message):
  _md5sum = "e13ef0559dc1ccb0a5a11bd1a53b8ab3"
  _type = "tb3_distributed_control/LeaderHistoryData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ROS话题优化版本：领导者历史数据消息类型

# 时间戳信息
float64 trajectory_time    # 轨迹相对时间（从0开始）
float64 ros_timestamp     # ROS时间戳

# 位置和姿态数据  
float64 x0               # 领导者x坐标
float64 y0               # 领导者y坐标
float64 theta0           # 领导者航向角

# 速度数据
float64 v0               # 线速度
float64 w0               # 角速度
float64 u0x              # x方向速度分量
float64 u0y              # y方向速度分量"""
  __slots__ = ['trajectory_time','ros_timestamp','x0','y0','theta0','v0','w0','u0x','u0y']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       trajectory_time,ros_timestamp,x0,y0,theta0,v0,w0,u0x,u0y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LeaderHistoryData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.trajectory_time is None:
        self.trajectory_time = 0.
      if self.ros_timestamp is None:
        self.ros_timestamp = 0.
      if self.x0 is None:
        self.x0 = 0.
      if self.y0 is None:
        self.y0 = 0.
      if self.theta0 is None:
        self.theta0 = 0.
      if self.v0 is None:
        self.v0 = 0.
      if self.w0 is None:
        self.w0 = 0.
      if self.u0x is None:
        self.u0x = 0.
      if self.u0y is None:
        self.u0y = 0.
    else:
      self.trajectory_time = 0.
      self.ros_timestamp = 0.
      self.x0 = 0.
      self.y0 = 0.
      self.theta0 = 0.
      self.v0 = 0.
      self.w0 = 0.
      self.u0x = 0.
      self.u0y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.trajectory_time, _x.ros_timestamp, _x.x0, _x.y0, _x.theta0, _x.v0, _x.w0, _x.u0x, _x.u0y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.trajectory_time, _x.ros_timestamp, _x.x0, _x.y0, _x.theta0, _x.v0, _x.w0, _x.u0x, _x.u0y,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.trajectory_time, _x.ros_timestamp, _x.x0, _x.y0, _x.theta0, _x.v0, _x.w0, _x.u0x, _x.u0y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.trajectory_time, _x.ros_timestamp, _x.x0, _x.y0, _x.theta0, _x.v0, _x.w0, _x.u0x, _x.u0y,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
