# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tb3_distributed_control/RobotHistoryData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotHistoryData(genpy.Message):
  _md5sum = "23ba331a962f095047cf39372dc8fff3"
  _type = "tb3_distributed_control/RobotHistoryData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ROS话题优化版本：机器人历史数据消息类型
# 设计目标：减少网络传输，提高实时性，降低roscore负载

# 机器人标识
int32 robot_id

# 时间戳信息
float64 trajectory_time    # 轨迹相对时间（从0开始）
float64 ros_timestamp     # ROS时间戳（用于数据时效性检查）

# 位置和姿态数据
float64 xc               # 当前x坐标
float64 yc               # 当前y坐标  
float64 thetac           # 当前航向角

# 控制输入数据
float64 vc               # 线速度
float64 wc               # 角速度

# 跟踪误差数据
float64 xe               # x方向误差
float64 ye               # y方向误差
float64 thetae           # 航向角误差

# 参考轨迹数据
float64 xr               # 参考x坐标
float64 yr               # 参考y坐标

# 观测器估计数据（对领导者位置的估计）
float64 zxeo_x           # 观测器估计的领导者X坐标
float64 zxeo_y           # 观测器估计的领导者Y坐标

# 避障相关数据（统一处理所有障碍物）
float64 raw_min_obstacle_distance   # 雷达原始数据的最小距离（直接从range获取）
float64 closest_obstacle_distance   # 最近障碍物点到参考点的距离（基于聚类分析）
int32 total_clusters_count          # 检测到的障碍物聚类总数
float64 avoidance_force_magnitude   # 避障力大小

# 性能分析数据
float64 computation_time  # 算法计算时间（秒）
float64 full_cycle_time  # 完整周期时间（秒）"""
  __slots__ = ['robot_id','trajectory_time','ros_timestamp','xc','yc','thetac','vc','wc','xe','ye','thetae','xr','yr','zxeo_x','zxeo_y','raw_min_obstacle_distance','closest_obstacle_distance','total_clusters_count','avoidance_force_magnitude','computation_time','full_cycle_time']
  _slot_types = ['int32','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robot_id,trajectory_time,ros_timestamp,xc,yc,thetac,vc,wc,xe,ye,thetae,xr,yr,zxeo_x,zxeo_y,raw_min_obstacle_distance,closest_obstacle_distance,total_clusters_count,avoidance_force_magnitude,computation_time,full_cycle_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotHistoryData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robot_id is None:
        self.robot_id = 0
      if self.trajectory_time is None:
        self.trajectory_time = 0.
      if self.ros_timestamp is None:
        self.ros_timestamp = 0.
      if self.xc is None:
        self.xc = 0.
      if self.yc is None:
        self.yc = 0.
      if self.thetac is None:
        self.thetac = 0.
      if self.vc is None:
        self.vc = 0.
      if self.wc is None:
        self.wc = 0.
      if self.xe is None:
        self.xe = 0.
      if self.ye is None:
        self.ye = 0.
      if self.thetae is None:
        self.thetae = 0.
      if self.xr is None:
        self.xr = 0.
      if self.yr is None:
        self.yr = 0.
      if self.zxeo_x is None:
        self.zxeo_x = 0.
      if self.zxeo_y is None:
        self.zxeo_y = 0.
      if self.raw_min_obstacle_distance is None:
        self.raw_min_obstacle_distance = 0.
      if self.closest_obstacle_distance is None:
        self.closest_obstacle_distance = 0.
      if self.total_clusters_count is None:
        self.total_clusters_count = 0
      if self.avoidance_force_magnitude is None:
        self.avoidance_force_magnitude = 0.
      if self.computation_time is None:
        self.computation_time = 0.
      if self.full_cycle_time is None:
        self.full_cycle_time = 0.
    else:
      self.robot_id = 0
      self.trajectory_time = 0.
      self.ros_timestamp = 0.
      self.xc = 0.
      self.yc = 0.
      self.thetac = 0.
      self.vc = 0.
      self.wc = 0.
      self.xe = 0.
      self.ye = 0.
      self.thetae = 0.
      self.xr = 0.
      self.yr = 0.
      self.zxeo_x = 0.
      self.zxeo_y = 0.
      self.raw_min_obstacle_distance = 0.
      self.closest_obstacle_distance = 0.
      self.total_clusters_count = 0
      self.avoidance_force_magnitude = 0.
      self.computation_time = 0.
      self.full_cycle_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i16di3d().pack(_x.robot_id, _x.trajectory_time, _x.ros_timestamp, _x.xc, _x.yc, _x.thetac, _x.vc, _x.wc, _x.xe, _x.ye, _x.thetae, _x.xr, _x.yr, _x.zxeo_x, _x.zxeo_y, _x.raw_min_obstacle_distance, _x.closest_obstacle_distance, _x.total_clusters_count, _x.avoidance_force_magnitude, _x.computation_time, _x.full_cycle_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 160
      (_x.robot_id, _x.trajectory_time, _x.ros_timestamp, _x.xc, _x.yc, _x.thetac, _x.vc, _x.wc, _x.xe, _x.ye, _x.thetae, _x.xr, _x.yr, _x.zxeo_x, _x.zxeo_y, _x.raw_min_obstacle_distance, _x.closest_obstacle_distance, _x.total_clusters_count, _x.avoidance_force_magnitude, _x.computation_time, _x.full_cycle_time,) = _get_struct_i16di3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i16di3d().pack(_x.robot_id, _x.trajectory_time, _x.ros_timestamp, _x.xc, _x.yc, _x.thetac, _x.vc, _x.wc, _x.xe, _x.ye, _x.thetae, _x.xr, _x.yr, _x.zxeo_x, _x.zxeo_y, _x.raw_min_obstacle_distance, _x.closest_obstacle_distance, _x.total_clusters_count, _x.avoidance_force_magnitude, _x.computation_time, _x.full_cycle_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 160
      (_x.robot_id, _x.trajectory_time, _x.ros_timestamp, _x.xc, _x.yc, _x.thetac, _x.vc, _x.wc, _x.xe, _x.ye, _x.thetae, _x.xr, _x.yr, _x.zxeo_x, _x.zxeo_y, _x.raw_min_obstacle_distance, _x.closest_obstacle_distance, _x.total_clusters_count, _x.avoidance_force_magnitude, _x.computation_time, _x.full_cycle_time,) = _get_struct_i16di3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i16di3d = None
def _get_struct_i16di3d():
    global _struct_i16di3d
    if _struct_i16di3d is None:
        _struct_i16di3d = struct.Struct("<i16di3d")
    return _struct_i16di3d
